### ISSUE TITLE
Tilt solution

### ISSUE THREAD

**Issue by faqndo97** [rwehresmann/static-pages#26]
Hey! I found you by the stackoverflow question, I'm looking here to see your entire tilt solution but seems that the branch does not exist anymore or was never pushed, can be?  I'm having a similar problem rendering erb on markdown and I was looking solutions.

Hope you are great!
Cheers,

**Comment by rwehresmann** [comment]
It's highly probable that I forgot to push the Tilt solution :P

It's been a while since I worked on this project, and I don't have it on my PC anymore. I'll try to find some time to check this question, though. As far as I can remember, the issue was easily solved with Tilt.
